### ISSUE TITLE
Doesn't work on recent Blender (4.0) API

### ISSUE THREAD

**Issue by Vittorio-Caggiano** [yuki-koyama/blender-cli-rendering#46]
Hi, thanks for sharing these scripts! I am a complete newbie to Blender and I really appreciate them.

I tried those scripts with the new Blender 4.0 and it seems this version introduced some major changes in the API which broke them.
```bash
Error: Python: Traceback (most recent call last):
  File "/test/blender-cli-rendering/10_mocap.py", line 137, in <module>
    utils.build_scene_composition(scene)
  File "/test/blender-cli-rendering/utils/composition.py", line 184, in build_scene_composition
    vignette_node = create_vignette_node(scene.node_tree)
  File "/test/blender-cli-rendering/utils/composition.py", line 165, in create_vignette_node
    vignette_node_group = add_vignette_node_group()
  File "/test/blender-cli-rendering/utils/composition.py", line 118, in add_vignette_node_group
    group.inputs.new("NodeSocketColor", "Image")
AttributeError: 'CompositorNodeTree' object has no attribute 'inputs'
Error: Cannot render, no camera
```

Would it be possible to have a version compatible with Blender 4.0?

**Comment by yuki-koyama** [comment]
Hi, I hope I will be able to have time to update the scripts for the latest Blender version (like 4.0), but I am currently busy with other stuff. PR is welcomed.

**Comment by Vittorio-Caggiano** [comment]
Thanks @yuki-koyama ! I will have a look but I am a complete newbie ... hope somebody else in the community might be able to help too!
